[build]
  base = "examples/demo"
  publish = "dist"
  command = "cd ../.. && bun install && cd examples/demo && bun install && bun run build"

[build.environment]
  NODE_VERSION = "18"

# Redirect all routes to index.html for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Build settings for different contexts
[context.production]
  command = "cd ../.. && bun install && cd examples/demo && bun install && bun run build"

[context.deploy-preview]
  command = "cd ../.. && bun install && cd examples/demo && bun install && bun run build"

[context.branch-deploy]
  command = "cd ../.. && bun install && cd examples/demo && bun install && bun run build" 